export const projects = [
  {
    title: 'MERN Application',
    description: "Using React, Node.js, Express & MongoDB you'll learn how to build a Full Stack MERN Application - from start to finish. The App is called Memories and it is a simple social media app that allows users to post interesting events that happened in their lives.",
      image: '/images/mern.png',
      tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://github.com/sanish65/MERN_Project.git',
    visit: 'https://google.com',
    id: 0,
  },
  {
    title: 'Drink-Vending REST-API',
    description: "Using React, Node.js, Express & MongoDB in typescript, demonstrating REST api, database handling and typescript implementation.",
      image: '/images/drinks.png',
      tags: ['Mongo', 'Express', 'React', 'Node', 'TypeScript'],
    source: 'https://github.com/sanish65/vending_machine-Mern_typescript.git',
    visit: 'https://google.com',
    id: 1,
  },
  {
    title: 'Simple Android Music-App',
    description:"it is a simple project built on android studio using java, that demonstrates simple music listing, playing and rendering.",
    image: '/images/Music.jpg',
    tags: ['java', 'android sdk'],
    source: 'https://github.com/sanish65/AndroidQuiz.git',
    visit: 'https://google.com',
    id: 2,
  },
  {
    title: 'Ecommerce',
    description: "This is a code repository for the development of inventory and ecommerce website that uses Nodejs server with mongoDB database and PUG/JADE as template engine rendering.",
      image: '/images/3.jpg',
      tags: ['PUG/JADE', 'nodeJs' ,'mongoDB'],
    source: 'https://github.com/sanish65/internE-commerce.git',
    visit: 'https://google.com',
    id: 3,
  },
  {
    title: 'Hotel Booking UI',
    description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    image: '/images/hotel.png',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://github.com/sanish65/hotelBookingUI.git',
    visit: 'https://google.com',
    id: 4,
  },
  {
    title: 'simple Youtube API',
    description: "This is a code repository i have used Youtube api to make own custom react-youtube",
    image: '/images/youtube.png',
    tags: ['React', 'Youtube v3 API'],
    source: 'https://github.com/sanish65/hotelBookingUI.git',
    visit: 'https://google.com',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2014, text: 'Finished School level Education', },
  { year: 2016, text: 'Completed +2', },
  { year: 2020, text: 'Started Internship as NodeJs Developer', },
  { year: 2021, text: 'Started Web development Career', },
];